{% set name = "downloader-cli" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/downloader_cli-{{ version }}.tar.gz
  sha256: 6c61dbf1203e18f63ec0a15aea3793dab764736dbe095b0893dc6d4a09e5df13

build:
  number: 0
  noarch: python
  entry_points:
    - dw = downloader_cli.download:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0
    - urllib3 >=1.25.6

test:
  imports:
    - downloader_cli
  commands:
    - pip check
    - dw --help
  requires:
    - pip

about:
  home: https://github.com/deepjyoti30/downloader-cli
  summary: A simple downloader written in Python with an awesome progressbar.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/deepjyoti30/downloader-cli

extra:
  recipe-maintainers:
    - HeavyTony2
