{% set name = "downloader-cli" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/downloader_cli-{{ version }}.tar.gz
  sha256: 61b40984da05ce0563721126fc7ff977dfdbb0c1bb875f8e9305765a5e49eddb

build:
  number: 1
  noarch: python
  entry_points:
    - dw = downloader_cli.main:main
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - urllib3 >=1.25.6

test:
  imports:
    - downloader_cli
  commands:
    - pip check
    - dw --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepjyoti30/downloader-cli
  summary: A simple downloader written in Python with an awesome progressbar.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/deepjyoti30/downloader-cli

extra:
  recipe-maintainers:
    - HeavyTony2
